name: Otomatik Deprem Guncelleme
on:
  schedule:
    - cron: '0 * * * *' # Her saat başı otomatik çalışır
  workflow_dispatch: # İstediğinde manuel çalıştırman için
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Paketleri Yukle
        run: pip install pandas requests gspread google-auth
      - name: Kodu Calistir
        env:
          GCP_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          SHEET_ID: '1QfRsf8YjsQnsCq1Gqwl3wXbDbgJxcv4sQGWsGx_G3zU'
        run: python update_script.py
